name: Dependabot 
on:
  workflow_dispatch:
  push:
    branches:
      - feat/dependabot 

jobs:
  sword-pulling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repos code
        uses: actions/checkout@v3

      - name: the excalibur
        env:
          THE_SECRET: ${{ secrets.GITHUB }}
        run: python scripts/the-secret.py